[versions]
accompanistFlowlayout = "0.36.0"
accompanistSystemuicontroller = "0.36.0"
agp = "9.0.0"
coil = "3.3.0"
coilCompose = "3.3.0"
components = "1.2.3"
composefadingedges = "1.0.4"
composeResources = "1.0.0-alpha01"
coreSplashscreen = "1.2.0"
datastorePreferences = "1.2.0"
desugar_jdk_libs_nio = "2.1.5"
gengolex = "2.7.0"
gson = "2.13.2"
hiltAndroid = "2.59.1"
hiltNavigationCompose = "1.3.0"
junitJupiter = "6.0.2"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
compose-preference = "1.1.1"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.4"
composeBom = "2026.02.00"
materialIconsExtended = "1.7.8"
media = "1.7.1"
media3Extractor = "1.9.2"
mockitoAndroid = "5.21.0"
navigationRuntimeKtx = "2.9.7"
navigationCompose = "2.9.7"
media3Common = "1.9.2"
lifecycleRuntimeComposeAndroid = "2.10.0"
newpipeextractor = "v0.25.2"
okhttp = "5.3.2"
roomRuntime = "2.8.4"
securityCrypto = "1.1.0"
tiamat = "2.2.0"
tiamatDestinations = "2.2.0"
timber = "5.0.1"
uiTestJunit4 = "1.10.3"
uiTestManifest = "1.10.3"
volley = "1.2.1"
shimmer = "1.0.0"

[libraries]
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanistFlowlayout" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Extractor" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Extractor" }
androidx-media3-extractor = { module = "androidx.media3:media3-extractor", version.ref = "media3Extractor" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Extractor" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
components = { module = "com.github.word-view:Components", version.ref = "components" }
compose-resources = { module = "com.github.ygorluizfrazao:compose-resources", version.ref = "composeResources" }
composefadingedges = { module = "com.github.GIGAMOLE:ComposeFadingEdges", version.ref = "composefadingedges" }
gengolex = { module = "com.github.word-view:Gengolex", version.ref = "gengolex" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android-compiler-v244 = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3Common" }
androidx-lifecycle-runtime-compose-android = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose-android", version.ref = "lifecycleRuntimeComposeAndroid" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
compose-preference = { module = "me.zhanghai.compose.preference:library", version.ref = "compose-preference" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
newpipeextractor = { module = "com.github.TeamNewPipe:NewPipeExtractor", version.ref = "newpipeextractor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
tiamat-destinations = { module = "io.github.composegears:tiamat-destinations", version.ref = "tiamatDestinations" }
tiamat = { module = "io.github.composegears:tiamat", version.ref = "tiamat" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
tools-desugar_jdk_libs_nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar_jdk_libs_nio" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
compose-shimmer = { module = "me.vponomarenko:compose-shimmer", version.ref = "shimmer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
legacy-kapt = { id = "com.android.legacy-kapt", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
